=== mdbox037a/cvesee/references/nvd_api_json_2.0_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "JSON Schema for NVD Vulnerability Data API version 2.2.3",
    "definitions": {
        "def_cve_item": {
            "properties": {
                "cve": {
                    "$ref": "#/definitions/cve_item"
                }
            },
            "required": [
                "cve"
            ],
            "additionalProperties": false
        },
        "cve_item": {
            "type": "object",
            "properties": {
                "id": {
                    "$ref": "#/definitions/cve_id"
                },
                "sourceIdentifier": {
                    "type": "string"
                },
                "vulnStatus": {
                    "type": "string"
                },
                "published": {
                    "type": "string",
                    "format": "date-time"
                },
                "lastModified": {
                    "type": "string",
                    "format": "date-time"
                },
                "evaluatorComment": {
                    "type": "string"
                },
                "evaluatorSolution": {
                    "type": "string"
                },
                "evaluatorImpact": {
                    "type": "string"
                },
                "cisaExploitAdd": {
                    "type": "string",
                    "format": "date"
                },
                "cisaActionDue": {
                    "type": "string",
                    "format": "date"
                },
                "cisaRequiredAction": {
                    "type": "string"
                },
                "cisaVulnerabilityName": {
                    "type": "string"
                },
                "cveTags": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "sourceIdentifier": {
                                "description": "The email address or UUID of the source that contributed the information",
                                "type": "string"
                            },
                            "tags": {
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "enum": [
                                        "unsupported-when-assigned",
                                        "exclusively-hosted-service",
                                        "disputed"
                                    ]
                                }
                            }
                        }
                    }
                },
                "descriptions": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/lang_string"
                    }
                },
                "references": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/reference"
                    }
                },
                "metrics": {
                    "description": "Metric scores for a vulnerability as found on NVD.",
                    "type": "object",
                    "properties": {
                        "cvssMetricV40": {
                            "description": "CVSS V4.0 score.",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cvss-v40"
                            }
                        },
                        "cvssMetricV31": {
                            "description": "CVSS V3.1 score.",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cvss-v31"
                            }
                        },
                        "cvssMetricV30": {
                            "description": "CVSS V3.0 score.",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cvss-v30"
                            }
                        },
                        "cvssMetricV2": {
                            "description": "CVSS V2.0 score.",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cvss-v2"
                            }
                        }
                    }
                },
                "weaknesses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/weakness"
                    }
                },
                "configurations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config"
                    }
                },
                "vendorComments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vendorComment"
                    }
                }
            },
            "required": [
                "id",
                "published",
                "lastModified",
                "references",
                "descriptions"
            ]
        },
        "cvss-v2": {
            "properties": {
                "source": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "Primary",
                        "Secondary"
                    ]
                },
                "cvssData": {
                    "$ref": "https://csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v2.0.json"
                },
                "baseSeverity": {
                    "type": "string"
                },
                "exploitabilityScore": {
                    "$ref": "#/definitions/def_subscore"
                },
                "impactScore": {
                    "$ref": "#/definitions/def_subscore"
                },
                "acInsufInfo": {
                    "type": "boolean"
                },
                "obtainAllPrivilege": {
                    "type": "boolean"
                },
                "obtainUserPrivilege": {
                    "type": "boolean"
                },
                "obtainOtherPrivilege": {
                    "type": "boolean"
                },
                "userInteractionRequired": {
                    "type": "boolean"
                }
            },
            "required": [
                "source",
                "type",
                "cvssData"
            ],
            "additionalProperties": false
        },
        "cvss-v30": {
            "properties": {
                "source": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "Primary",
                        "Secondary"
                    ]
                },
                "cvssData": {
                    "$ref": "https://csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v3.0.json"
                },
                "exploitabilityScore": {
                    "$ref": "#/definitions/def_subscore"
                },
                "impactScore": {
                    "$ref": "#/definitions/def_subscore"
                }
            },
            "required": [
                "source",
                "type",
                "cvssData"
            ],
            "additionalProperties": false
        },
        "cvss-v31": {
            "properties": {
                "source": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "Primary",
                        "Secondary"
                    ]
                },
                "cvssData": {
                    "$ref": "https://csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v3.1.json"
                },
                "exploitabilityScore": {
                    "$ref": "#/definitions/def_subscore"
                },
                "impactScore": {
                    "$ref": "#/definitions/def_subscore"
                }
            },
            "required": [
                "source",
                "type",
                "cvssData"
            ],
            "additionalProperties": false
        },
        "cvss-v40": {
            "properties": {
                "source": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "Primary",
                        "Secondary"
                    ]
                },
                "cvssData": {
                    "$ref": "https://csrc.nist.gov/schema/nvd/api/2.0/external/cvss-v4.0.json"
                }
            },
            "required": [
                "source",
                "type",
                "cvssData"
            ],
            "additionalProperties": false
        },
        "cve_id": {
            "type": "string",
            "pattern": "^CVE-[0-9]{4}-[0-9]{4,}$"
        },
        "lang_string": {
            "type": "object",
            "properties": {
                "lang": {
                    "type": "string"
                },
                "value": {
                    "type": "string",
                    "maxLength": 4096
                }
            },
            "required": [
                "lang",
                "value"
            ],
            "additionalProperties": false
        },
        "reference": {
            "type": "object",
            "properties": {
                "url": {
					"type": "string",
					"format": "uri",
					"minLength": 1,
					"maxLength": 2048
                },
                "source": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "url"
            ]
        },
        "vendorComment": {
            "type": "object",
            "properties": {
                "organization": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "lastModified": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "organization",
                "comment",
                "lastModified"
            ],
            "additionalProperties": false
        },
        "weakness": {
            "properties": {
                "source": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "description": {
                    "type": "array",
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/lang_string"
                    }
                }
            },
            "required": [
                "source",
                "type",
                "description"
            ],
            "additionalProperties": false
        },
        "config": {
            "properties": {
                "operator": {
                    "type": "string",
                    "enum": [
                        "AND",
                        "OR"
                    ]
                },
                "negate": {
                    "type": "boolean"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                }
            },
            "required": [
                "nodes"
            ]
        },
        "node": {
            "description": "Defines a configuration node in an NVD applicability statement.",
            "properties": {
                "operator": {
                    "type": "string",
                    "enum": [
                        "AND",
                        "OR"
                    ]
                },
                "negate": {
                    "type": "boolean"
                },
                "cpeMatch": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cpe_match"
                    }
                }
            },
            "required": [
                "operator",
                "cpeMatch"
            ]
        },
        "cpe_match": {
            "description": "CPE match string or range",
            "type": "object",
            "properties": {
                "vulnerable": {
                    "type": "boolean"
                },
                "criteria": {
                    "type": "string"
                },
                "matchCriteriaId": {
                    "type": "string",
                    "format": "uuid"
                },
                "versionStartExcluding": {
                    "type": "string"
                },
                "versionStartIncluding": {
                    "type": "string"
                },
                "versionEndExcluding": {
                    "type": "string"
                },
                "versionEndIncluding": {
                    "type": "string"
                }
            },
            "required": [
                "vulnerable",
                "criteria",
                "matchCriteriaId"
            ]
        },
        "def_subscore": {
            "description": "CVSS subscore.",
            "type": "number",
            "minimum": 0,
            "maximum": 10
        }
    },
    "type": "object",
    "properties": {
        "resultsPerPage": {
            "type": "integer"
        },
        "startIndex": {
            "type": "integer"
        },
        "totalResults": {
            "type": "integer"
        },
        "format": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time"
        },
        "vulnerabilities": {
            "description": "NVD feed array of CVE",
            "type": "array",
            "items": {
                "$ref": "#/definitions/def_cve_item"
            }
        }
    },
    "required": [
        "resultsPerPage",
        "startIndex",
        "totalResults",
        "format",
        "version",
        "timestamp",
        "vulnerabilities"
    ],
    "additionalProperties": false
}

=== mdbox037a/cvesee/references/examples/cvssV2_example.json
{
  "resultsPerPage": 1,
  "startIndex": 0,
  "totalResults": 1,
  "format": "NVD_CVE",
  "version": "2.0",
  "timestamp": "2026-04-08T02:27:55.449",
  "vulnerabilities": [
    {
      "cve": {
        "id": "CVE-1999-0095",
        "sourceIdentifier": "cve@mitre.org",
        "published": "1988-10-01T04:00:00.000",
        "lastModified": "2025-04-03T01:03:51.193",
        "vulnStatus": "Deferred",
        "cveTags": [],
        "descriptions": [
          {
            "lang": "en",
            "value": "The debug command in Sendmail is enabled, allowing attackers to execute commands as root."
          },
          {
            "lang": "es",
            "value": "El comando de depuración de Sendmail está activado, permitiendo a atacantes ejecutar comandos como root."
          }
        ],
        "metrics": {
          "cvssMetricV2": [
            {
              "source": "nvd@nist.gov",
              "type": "Primary",
              "cvssData": {
                "version": "2.0",
                "vectorString": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
                "baseScore": 10.0,
                "accessVector": "NETWORK",
                "accessComplexity": "LOW",
                "authentication": "NONE",
                "confidentialityImpact": "COMPLETE",
                "integrityImpact": "COMPLETE",
                "availabilityImpact": "COMPLETE"
              },
              "baseSeverity": "HIGH",
              "exploitabilityScore": 10.0,
              "impactScore": 10.0,
              "acInsufInfo": false,
              "obtainAllPrivilege": true,
              "obtainUserPrivilege": false,
              "obtainOtherPrivilege": false,
              "userInteractionRequired": false
            }
          ]
        },
        "weaknesses": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "description": [
              {
                "lang": "en",
                "value": "NVD-CWE-Other"
              }
            ]
          }
        ],
        "configurations": [
          {
            "nodes": [
              {
                "operator": "OR",
                "negate": false,
                "cpeMatch": [
                  {
                    "vulnerable": true,
                    "criteria": "cpe:2.3:a:eric_allman:sendmail:5.58:*:*:*:*:*:*:*",
                    "matchCriteriaId": "1D07F493-9C8D-44A4-8652-F28B46CBA27C"
                  }
                ]
              }
            ]
          }
        ],
        "references": [
          {
            "url": "http://seclists.org/fulldisclosure/2019/Jun/16",
            "source": "cve@mitre.org"
          },
          {
            "url": "http://www.openwall.com/lists/oss-security/2019/06/05/4",
            "source": "cve@mitre.org"
          },
          {
            "url": "http://www.openwall.com/lists/oss-security/2019/06/06/1",
            "source": "cve@mitre.org"
          },
          {
            "url": "http://www.osvdb.org/195",
            "source": "cve@mitre.org"
          },
          {
            "url": "http://www.securityfocus.com/bid/1",
            "source": "cve@mitre.org"
          },
          {
            "url": "http://seclists.org/fulldisclosure/2019/Jun/16",
            "source": "af854a3a-2127-422b-91ae-364da2661108"
          },
          {
            "url": "http://www.openwall.com/lists/oss-security/2019/06/05/4",
            "source": "af854a3a-2127-422b-91ae-364da2661108"
          },
          {
            "url": "http://www.openwall.com/lists/oss-security/2019/06/06/1",
            "source": "af854a3a-2127-422b-91ae-364da2661108"
          },
          {
            "url": "http://www.osvdb.org/195",
            "source": "af854a3a-2127-422b-91ae-364da2661108"
          },
          {
            "url": "http://www.securityfocus.com/bid/1",
            "source": "af854a3a-2127-422b-91ae-364da2661108"
          }
        ]
      }
    }
  ]
}

=== mdbox037a/cvesee/references/examples/cvssV3_example.json
{
  "resultsPerPage": 1,
  "startIndex": 0,
  "totalResults": 1,
  "format": "NVD_CVE",
  "version": "2.0",
  "timestamp": "2026-04-08T02:29:31.192",
  "vulnerabilities": [
    {
      "cve": {
        "id": "CVE-2017-1253",
        "sourceIdentifier": "psirt@us.ibm.com",
        "published": "2017-07-05T18:29:00.467",
        "lastModified": "2025-04-20T01:37:25.860",
        "vulnStatus": "Deferred",
        "cveTags": [],
        "descriptions": [
          {
            "lang": "en",
            "value": "IBM Security Guardium 10.0 could allow a remote authenticated attacker to execute arbitrary commands on the system. By sending a specially-crafted request, an attacker could exploit this vulnerability to execute arbitrary commands on the system. IBM X-Force ID: 124633."
          },
          {
            "lang": "es",
            "value": "IBM Security Guardium 10.0 permite a un usuario remoto autenticado ejecutar comandos aleatorios en el sistema. Mediante el envió de solicitudes especialmente manipuladas, un atacante podría ejecutar comando aleatorios en el sistema. IBM X-Force ID: 124633."
          }
        ],
        "metrics": {
          "cvssMetricV30": [
            {
              "source": "nvd@nist.gov",
              "type": "Primary",
              "cvssData": {
                "version": "3.0",
                "vectorString": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:H",
                "baseScore": 9.9,
                "baseSeverity": "CRITICAL",
                "attackVector": "NETWORK",
                "attackComplexity": "LOW",
                "privilegesRequired": "LOW",
                "userInteraction": "NONE",
                "scope": "CHANGED",
                "confidentialityImpact": "HIGH",
                "integrityImpact": "HIGH",
                "availabilityImpact": "HIGH"
              },
              "exploitabilityScore": 3.1,
              "impactScore": 6.0
            }
          ],
          "cvssMetricV2": [
            {
              "source": "nvd@nist.gov",
              "type": "Primary",
              "cvssData": {
                "version": "2.0",
                "vectorString": "AV:N/AC:L/Au:S/C:P/I:P/A:P",
                "baseScore": 6.5,
                "accessVector": "NETWORK",
                "accessComplexity": "LOW",
                "authentication": "SINGLE",
                "confidentialityImpact": "PARTIAL",
                "integrityImpact": "PARTIAL",
                "availabilityImpact": "PARTIAL"
              },
              "baseSeverity": "MEDIUM",
              "exploitabilityScore": 8.0,
              "impactScore": 6.4,
              "acInsufInfo": false,
              "obtainAllPrivilege": false,
              "obtainUserPrivilege": false,
              "obtainOtherPrivilege": false,
              "userInteractionRequired": false
            }
          ]
        },
        "weaknesses": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "description": [
              {
                "lang": "en",
                "value": "CWE-78"
              }
            ]
          }
        ],
        "configurations": [
          {
            "nodes": [
              {
                "operator": "OR",
                "negate": false,
                "cpeMatch": [
                  {
                    "vulnerable": true,
                    "criteria": "cpe:2.3:a:ibm:security_guardium:10.0:*:*:*:*:*:*:*",
                    "matchCriteriaId": "552A0A69-388F-4842-A882-78F267D4BF09"
                  },
                  {
                    "vulnerable": true,
                    "criteria": "cpe:2.3:a:ibm:security_guardium:10.0.1:*:*:*:*:*:*:*",
                    "matchCriteriaId": "B9ACD03A-8D4C-4B94-81AB-D1BBD41E0182"
                  },
                  {
                    "vulnerable": true,
                    "criteria": "cpe:2.3:a:ibm:security_guardium:10.1:*:*:*:*:*:*:*",
                    "matchCriteriaId": "148A8443-DF7A-42AA-8D86-128CCC1D871E"
                  },
                  {
                    "vulnerable": true,
                    "criteria": "cpe:2.3:a:ibm:security_guardium:10.1.2:*:*:*:*:*:*:*",
                    "matchCriteriaId": "45E6B962-F8F8-4979-BC76-AE0B16EEB082"
                  }
                ]
              }
            ]
          }
        ],
        "references": [
          {
            "url": "http://www.ibm.com/support/docview.wss?uid=swg22004426",
            "source": "psirt@us.ibm.com",
            "tags": [
              "Vendor Advisory"
            ]
          },
          {
            "url": "http://www.securityfocus.com/bid/99372",
            "source": "psirt@us.ibm.com",
            "tags": [
              "Third Party Advisory",
              "VDB Entry"
            ]
          },
          {
            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/124633",
            "source": "psirt@us.ibm.com",
            "tags": [
              "VDB Entry",
              "Vendor Advisory"
            ]
          },
          {
            "url": "http://www.ibm.com/support/docview.wss?uid=swg22004426",
            "source": "af854a3a-2127-422b-91ae-364da2661108",
            "tags": [
              "Vendor Advisory"
            ]
          },
          {
            "url": "http://www.securityfocus.com/bid/99372",
            "source": "af854a3a-2127-422b-91ae-364da2661108",
            "tags": [
              "Third Party Advisory",
              "VDB Entry"
            ]
          },
          {
            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/124633",
            "source": "af854a3a-2127-422b-91ae-364da2661108",
            "tags": [
              "VDB Entry",
              "Vendor Advisory"
            ]
          }
        ]
      }
    }
  ]
}
